### ISSUE TITLE
Can't use empty string as thousands separator

### ISSUE THREAD

**Issue by wraithy** [leekchan/accounting#8]
```
if accounting.Thousand == "" {
	accounting.Thousand = ","
}
```
Surely this is a big use case?

**Comment by leekchan** [comment]
Thanks for your feedback. I'll add support for it in the next version.

**Comment by Dexus** [comment]
@leekchan I would like to add this to my PR #11 What do you think? Would it be ok for you?

**Comment by leekchan** [comment]
@Dexus Sure :)

**Comment by Dexus** [comment]
Should be fixed with db805ec after merge.

**Comment by leekchan** [comment]
@wraithy @Dexus The pr has been merged. Thanks @Dexus !! 👍

**Comment by ChristianGerdes** [comment]
This is still an issue. When attempting to set the thousand separator to an empty string, it still shows.

```
currency := accounting.Accounting{
	Symbol:    "",
	Precision: 2,
	Thousand:  "",
	Decimal:   ".",
}

currency.FormatMoney(10000)
```

Expected output:
``1000.00``

Actual output:
``1,000.00``

**Comment by ghiewa** [comment]
> This is still an issue. When attempting to set the thousand separator to an empty string, it still shows.
> 
> ```
> currency := accounting.Accounting{
> 	Symbol:    "",
> 	Precision: 2,
> 	Thousand:  "",
> 	Decimal:   ".",
> }
> 
> currency.FormatMoney(10000)
> ```
> 
> Expected output: `1000.00`
> 
> Actual output: `1,000.00`

try this way,
currency := accounting.DefaultAccounting("", 2)
currency.Decimal="."
currency.SetThousandSeparator("")

currency.FormatMoney(10000)
